server:
  port: 8081

topic:
  name: ${TOPIC_NAME}

spring:
  kafka:
    consumer:
      group-id: "default"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}